### ISSUE TITLE
Conditional sampling from DDPM

### ISSUE THREAD

**Issue by dionman** [vanderschaarlab/synthcity#175]
@TZTsai 
` "RuntimeError: Conditional mismatch. Got inference conditional, without any training conditional"` is being raised when training the DDPM with `is_classification=True` and trying to generate samples from it with an explicit `cond` vector. Could you please have a look at it, or write an example where a DDPM is fitted conditioned on a categorical column and subsequently asked to generate samples given a specified cond? I also tried to fit using alternatively an explicit cond (with `is_classification=False`), however in that case I get errors related to the dtype of the cond (apparently this seems to be currently supported only for numerical columns).

**Comment by TZTsai** [comment]
@dionman 
Which version are you using? Could you try the [latest version](https://github.com/TZTsai/synthcity/tree/tab_ddpm) in my fork? `RuntimeError: Conditional mismatch. Got inference conditional, without any training conditional` is probably due to a previous bug that the Plugin requires an explicit `cond` argument during `fit` if you want to generate with a `cond` as well, but DDPM automatically sets the labels as the `cond` if `is_classification=True`. This has already been fixed.

For the second problem, yes the `cond` should have a float or int data type for the moment, because otherwise it needs one-hot encoding, while in the diffusion model it is assumed to be 1-dimensional. Perhaps you can also use `LabelEncoder` to encode the `cond` if it has an `object` dtype and provide it to the `fit` method as follows.
![图片](https://user-images.githubusercontent.com/34415979/230451573-cb09a14d-d4eb-4b03-83b0-4059d488fe04.png)

**Comment by dionman** [comment]
I'm using release v0.2.5. Is it fixed at this version of the code?

**Comment by TZTsai** [comment]
> I'm using release v0.2.5. Is it fixed at this version of the code?

I checked that commit. Sorry it is not fixed there.

**Comment by dionman** [comment]
okay, what workaround should I use at the moment? Import the library from your module?

**Comment by TZTsai** [comment]
You can replace Line 203-224 in [src/synthcity/plugins/generic/plugin_ddpm.py](https://github.com/vanderschaarlab/synthcity/compare/v0.2.4...v0.2.5#diff-0e95ae832a4114b2562e85eaef763cef3d55201570d466482f01e0e005b41d16) with the following code:
```python
        if args:
            raise ValueError("Only keyword arguments are allowed")

        if self.is_classification:
            if cond is not None:
                raise ValueError(
                    "cond is already given by the labels for classification"
                )
            df, cond = X.unpack()
            self._labels, self._cond_dist = np.unique(cond, return_counts=True)
            self._cond_dist = self._cond_dist / self._cond_dist.sum()
            self.target_name = cond.name

        df = self.encoder.fit_transform(df)

        if cond is not None:
            if type(cond) is str:
                cond = df[cond]
            cond = pd.Series(cond, index=df.index)
            self.expecting_conditional = True

        # NOTE: cond may also be included in the dataframe
        self.model.fit(df, cond, **kwargs)
        self.loss_history = self.model.loss_history

        return self
```

**Comment by dionman** [comment]
do you mean lines 218-224?

**Comment by TZTsai** [comment]
> do you mean lines 218-224?

No, should be from line 214, starting with `else:`.

**Comment by dionman** [comment]
This raises ```'TabDDPMPlugin' object has no attribute 'encoder'```

**Comment by dionman** [comment]
https://github.com/TZTsai/synthcity/blob/e336d3cd42516cef27ac4ad60ac0df61bd92f1a6/src/synthcity/plugins/generic/plugin_ddpm.py#L157
self.encoder also needs to be added earlier in this script

**Comment by TZTsai** [comment]
> [TZTsai/synthcity@`e336d3c`/src/synthcity/plugins/generic/plugin_ddpm.py#L157](https://github.com/TZTsai/synthcity/blob/e336d3cd42516cef27ac4ad60ac0df61bd92f1a6/src/synthcity/plugins/generic/plugin_ddpm.py#L157) `self.encoder` also needs to be added earlier in this script ...which implies changing a few more things

Sorry I forget about that. You can comment that line for the moment. Can it run after that?

**Comment by dionman** [comment]
Thanks. Is there any cleaner way to enable this after the most recent commits in the main?

**Comment by TZTsai** [comment]
Sorry I just found my last reply wasn't sent out, probably due to internet reasons. In the latest version of the main branch, this should work fine. Have you checked it?

**Comment by dionman** [comment]
thanks, yes, this works
