### ISSUE TITLE
Add support for pip 23.1 in workflows

### ISSUE THREAD

**Issue by robsdavis** [vanderschaarlab/synthcity#183]
## Description
Currently, upgrading pip to 23.1 causes a fail in the .github/workflows, so the version of pip is pinned to 23.0.1. This constraint should be removed.

**Comment by TZTsai** [comment]
It seems that the failure of importing torch in building the wheel of geomloss may be related to the version of "wheel" or "setuptool". After it runs the following commands, there is no longer this error. I'm not sure what is the real cause of this problem, because yesterday the workflow was free of this error without upgrading "wheel" or "setuptool" as well.

![图片](https://user-images.githubusercontent.com/34415979/233345788-7d281742-3adc-4131-9b3a-b46121d3804b.png)

**Comment by TZTsai** [comment]
So by upgrading "setuptools" and "wheel" the dependencies can be successfully installed with pip 23.1; otherwise there will be an ImportError of torch when building geomloss. Keeping pip version to 23.0.1 also worked, so I think a possible explanation is that the newest versions of "setuptools" or "wheel" must be installed to match the new release of pip 23.1. But it is just hypothetical.

**Comment by robsdavis** [comment]
This is fixed by #178. Thanks @TZTsai
