### ISSUE TITLE
[Models] Add TabNet support

### ISSUE THREAD

**Issue by bcebere** [vanderschaarlab/synthcity#27]
https://github.com/dreamquark-ai/tabnet

**Comment by ZhaozhiQIAN** [comment]
Hi @bcebere , wondering what's the best way to add this functionality. 

The most obvious way is to create a class TabNet, similar to the MLP class. Then, I need to change all the classes that use MLP to have the option for using TabNet instead (for instance, plugins/core/models/gan). However, TabNet will require a set of additional hyper-parameters, which should be passed to the class's __init__ method (just as generator_n_units_hidden).  Is there a neat way of doing so without bloating the list of arguments?

**Comment by TZTsai** [comment]
Hello! I am trying to add this plugin in my fork now. I will send a pull request when it's ready.

**Comment by TZTsai** [comment]
I have added the TabNet model now. As @ZhaozhiQIAN said, it is added as a building block in other models, similar to MLP. Therefore only the multi-step attention encoder is used, and the random obfuscator and the decoder are neglected as they are used for self-supervised pre-training. I tried using TabNet instead of MLP as the diffusion model in TabDDPM, but although it passed all preceeding tests, the final test checking the evaluation performance given by XGBoost failed.
